//! Measurement binary: quantify unreachable free regions in `spicy` maps.
//!
//! Generates N maps with the same generator the simulator uses, applies the
//! start-carve from `Win::new_headless`, then flood-fills from the fixed
//! trainer start (132, 36) and reports:
//!   - fraction of maps that contain any unreachable free cell
//!   - mean and max fraction of free area that is unreachable
//!
//! Run with: `cargo run --release --bin spicy_reach`
//! 
//! Originally generated by Claude Code Opus 4.7 xHigh, then verified and
//! modified by the authors.

use std::collections::VecDeque;

use rand::rngs::SmallRng;
use rand::SeedableRng;

use util::{coords, dist, inv_coords_f32, Rect, HEIGHT, WIDTH};

mod spicy;

const CARVE: f32 = 21.0;
const START: (f32, f32) = (132.0, 36.0);
const N_MAPS: usize = 500;

fn main() {
    let mut n_with_unreachable = 0usize;
    let mut sum_frac_unreach = 0.0f64;
    let mut max_frac = 0.0f64;
    let mut max_seed = 0u64;
    let mut sum_free = 0usize;
    let mut sum_unreach_cells = 0usize;

    for seed in 0..N_MAPS as u64 {
        let mut rng = SmallRng::seed_from_u64(seed);
        let mut obs: Vec<Rect> = Vec::new();
        spicy::gen_obs(&mut rng, &mut obs);

        // Rasterize: true = obstacle.
        let mut mask = vec![false; WIDTH * HEIGHT];
        for r in &obs {
            for i in r.to_fb() {
                if i < mask.len() { mask[i] = true; }
            }
        }
        // Win's start-carve: clear any obstacle within CARVE of START.
        for i in 0..mask.len() {
            if mask[i] {
                let p = inv_coords_f32(i as u32);
                if dist(p, START) < CARVE { mask[i] = false; }
            }
        }

        let free_total = mask.iter().filter(|b| !**b).count();

        let start_idx = coords(START.0 as u32, START.1 as u32) as usize;
        if mask[start_idx] { continue; } // start-carve should prevent this

        // 4-connected BFS over free cells. Buffer indices are contiguous in a
        // row-major layout (with y flipped), so (i%W, i/W) works as (col, row).
        let mut visited = vec![false; WIDTH * HEIGHT];
        let mut queue = VecDeque::new();
        visited[start_idx] = true;
        queue.push_back(start_idx);
        let mut reached = 0usize;
        while let Some(i) = queue.pop_front() {
            reached += 1;
            let x = (i % WIDTH) as i32;
            let y = (i / WIDTH) as i32;
            for (dx, dy) in [(-1, 0), (1, 0), (0, -1), (0, 1)] {
                let nx = x + dx;
                let ny = y + dy;
                if nx < 0 || ny < 0 || nx >= WIDTH as i32 || ny >= HEIGHT as i32 { continue; }
                let ni = (ny as usize) * WIDTH + (nx as usize);
                if visited[ni] || mask[ni] { continue; }
                visited[ni] = true;
                queue.push_back(ni);
            }
        }

        let unreachable = free_total.saturating_sub(reached);
        let frac = unreachable as f64 / free_total as f64;
        if unreachable > 0 { n_with_unreachable += 1; }
        sum_frac_unreach += frac;
        sum_free += free_total;
        sum_unreach_cells += unreachable;
        if frac > max_frac { max_frac = frac; max_seed = seed; }
        eprintln!("{:.2}", frac * 100.0);
    }

    let mean_free = sum_free as f64 / N_MAPS as f64;
    let mean_unreach_cells = sum_unreach_cells as f64 / N_MAPS as f64;
    let mean_frac = sum_frac_unreach / N_MAPS as f64;
    let pct_with = 100.0 * n_with_unreachable as f64 / N_MAPS as f64;

    println!("Spicy reachability: N = {} maps, start = ({}, {}), carve = {}",
        N_MAPS, START.0, START.1, CARVE);
    println!(
        "  Mean free cells per map: {:.0} ({:.1}% of {}x{} grid)",
        mean_free, 100.0 * mean_free / (WIDTH * HEIGHT) as f64, WIDTH, HEIGHT,
    );
    println!(
        "  Maps with any unreachable free cells: {} / {} ({:.1}%)",
        n_with_unreachable, N_MAPS, pct_with,
    );
    println!(
        "  Mean unreachable cells per map: {:.1}",
        mean_unreach_cells,
    );
    println!(
        "  Mean fraction of free area unreachable: {:.3}%",
        100.0 * mean_frac,
    );
    println!(
        "  Max fraction of free area unreachable: {:.3}% (seed {})",
        100.0 * max_frac, max_seed,
    );
}
