//! Spicy map generator: anisotropic thin walls at moderate density.
//!
//! Reproduces the geometric character of the `d = 0.15` setting from the old
//! anisotropic-rect occlusion generator: thickness-2 rectangles with lengths
//! drawn from a jittered scale around 0.15, placed at random positions and
//! orientations, filled until raw obstacle coverage hits ~15% of grid cells.
//! This was the map class that produced the highest measured occlusion (~0.74
//! at short range) in the previous sweep.
//!
//! After placement, a morphological closing pass with radius `CLOSE_R = 2`
//! fills any free-space gap narrower than `2*CLOSE_R + 1 = 5` px between
//! disconnected obstacle regions. Gaps of 5 px or wider stay intact. Rects
//! themselves may still overlap or touch during placement — closing only
//! adds cells, never removes them.
//!
//! Deliberately excludes the "enforce single reachable-free component" step
//! that the occlusion branch performed — that step was the source of the
//! giant filled-blob artefacts. Isolated pockets are allowed; Win's 40-cell
//! start-carve keeps the robot's neighbourhood clear.
//! 
//! Originally generated by Claude Code Opus 4.7 xHigh, then verified and
//! modified by the authors.

use rand::prelude::*;
use rand::rngs::SmallRng;

use util::{Rect, W32, H32, WIDTH, HEIGHT};

/// Target obstacle coverage as a fraction of grid cells (unique cells only —
/// overlap between rectangles is counted once). Actual final coverage after
/// the closing pass will be somewhat higher because closing fills gaps.
const TARGET_COVERAGE: f32 = 0.15;

/// Nominal anisotropy knob. 0.15 → length uniform in ~[6, 31], thickness 2.
const D: f32 = 0.15;

/// Additive jitter applied to `D` per rectangle. Widens the shape distribution
/// so the map is not visually stripey.
const JITTER: f32 = 0.15;

/// Length range in grid cells. `long_min` is the minimum rectangle major-axis
/// length; `long_max` is the value the schedule would reach at scale=1.0.
const LONG_MIN: u32 = 6;
const LONG_MAX: u32 = 90;

/// Rectangle short axis (matches the robot's `lsc` thickness).
const THICKNESS: u32 = 2;

/// Safety cap on placement attempts. A well-behaved run finishes in ~200
/// rectangles; this ceiling only triggers when TARGET_COVERAGE is unreachable
/// because of aggressive overlap avoidance.
const MAX_RECTS: usize = 5000;

/// Structuring-element radius for the post-placement closing pass. Gaps of
/// width `<= 2 * CLOSE_R` px between disconnected obstacle regions get
/// filled. With `CLOSE_R = 2`, any gap narrower than 5 px is closed; the
/// smallest surviving gap has width 5.
const CLOSE_R: usize = 2;

/// Populate `obs` with anisotropic rectangles until unique-cell obstacle
/// coverage reaches `TARGET_COVERAGE`, then apply a morphological closing
/// pass that fills any narrow (< 5 px) gaps. Caller (typically `Win`) is
/// responsible for rasterizing `obs` into the pixel buffer and applying any
/// start-carve.
pub fn gen_obs(rng: &mut SmallRng, obs: &mut Vec<Rect>) {
    let total_cells = WIDTH * HEIGHT;
    let target = (TARGET_COVERAGE * total_cells as f32) as usize;

    // Occupancy mask, `true` = obstacle. Used to count unique cells during
    // placement AND to run the closing pass. `obs` is the authoritative
    // output; we sync closing-added cells back into `obs` as 1×1 rects.
    let mut mask = vec![false; total_cells];
    let mut covered = 0usize;

    for _ in 0..MAX_RECTS {
        if covered >= target { break; }

        // Shape: length grows with (D + jitter); thickness fixed at 2.
        let jitter: f32 = rng.gen_range(-JITTER..JITTER);
        let scale = (D + jitter).clamp(0.0, 1.0);
        let length = LONG_MIN + ((LONG_MAX - LONG_MIN) as f32 * scale) as u32;

        let horizontal = rng.gen_bool(0.5);
        let (w, h) = if horizontal {
            (length, THICKNESS)
        } else {
            (THICKNESS, length)
        };

        // Anywhere on the grid; the min-cap of 1 on the upper bound prevents
        // gen_range from panicking when a rect matches or exceeds the grid.
        let x = rng.gen_range(0..W32.saturating_sub(w).max(1));
        let y = rng.gen_range(0..H32.saturating_sub(h).max(1));
        let rect = Rect { coords: (x, y), width: w, height: h };

        for i in rect.to_fb() {
            if i < mask.len() && !mask[i] {
                mask[i] = true;
                covered += 1;
            }
        }
        obs.push(rect);
    }

    // Morphological closing: for every free cell, if all cells within CLOSE_R
    // of it are obstacles after a dilation-by-CLOSE_R pass, mark it obstacle.
    // Effect: gaps of width < 2*CLOSE_R+1 = 5 px between disconnected regions
    // get bridged; gaps of width >= 5 remain intact. Only ever ADDS cells.
    let dilated = dilate(&mask, CLOSE_R);
    let closed = erode(&dilated, CLOSE_R);

    // Emit a 1×1 Rect for each cell that closing added. Win rasterizes these
    // like any other rect, so the closed mask is what the robot sees.
    for i in 0..mask.len() {
        if closed[i] && !mask[i] {
            let (x, y) = buf_index_to_world(i);
            obs.push(Rect { coords: (x, y), width: 1, height: 1 });
        }
    }
}

/// Dilation: output cell is true if ANY cell within radius `r` (Chebyshev /
/// square neighbourhood) is true in the input. Out-of-bounds cells are
/// treated as false (no obstacle beyond the map).
fn dilate(mask: &[bool], r: usize) -> Vec<bool> {
    let mut out = vec![false; mask.len()];
    let r = r as i32;
    for y in 0..HEIGHT as i32 {
        for x in 0..WIDTH as i32 {
            let mut any = false;
            'k: for dy in -r..=r {
                for dx in -r..=r {
                    let nx = x + dx;
                    let ny = y + dy;
                    if nx < 0 || nx >= WIDTH as i32 || ny < 0 || ny >= HEIGHT as i32 { continue; }
                    let idx = util::coords(nx as u32, ny as u32) as usize;
                    if idx < mask.len() && mask[idx] {
                        any = true;
                        break 'k;
                    }
                }
            }
            let idx = util::coords(x as u32, y as u32) as usize;
            if idx < out.len() { out[idx] = any; }
        }
    }
    out
}

/// Erosion: output cell is true only if ALL cells within radius `r` are true
/// in the input. Out-of-bounds cells are treated as true (obstacle beyond the
/// map) so we don't shrink obstacles that legitimately touch the map edge.
fn erode(mask: &[bool], r: usize) -> Vec<bool> {
    let mut out = vec![false; mask.len()];
    let r = r as i32;
    for y in 0..HEIGHT as i32 {
        for x in 0..WIDTH as i32 {
            let mut all = true;
            'k: for dy in -r..=r {
                for dx in -r..=r {
                    let nx = x + dx;
                    let ny = y + dy;
                    // OOB → treat as obstacle (don't erode edge-touching obstacles).
                    if nx < 0 || nx >= WIDTH as i32 || ny < 0 || ny >= HEIGHT as i32 { continue; }
                    let idx = util::coords(nx as u32, ny as u32) as usize;
                    if idx < mask.len() && !mask[idx] {
                        all = false;
                        break 'k;
                    }
                }
            }
            let idx = util::coords(x as u32, y as u32) as usize;
            if idx < out.len() { out[idx] = all; }
        }
    }
    out
}

/// Inverse of `util::coords(x, y) = x + (H32 - y - 1) * W32`. Yields world
/// coords (x, y) for a given buffer index. Used to emit 1×1 rects at
/// closing-added cells so that round-tripping through `Rect::to_fb` lands
/// back at the same buffer index.
fn buf_index_to_world(i: usize) -> (u32, u32) {
    let x = (i % WIDTH) as u32;
    let y_stored = (i / WIDTH) as u32;
    (x, H32 - 1 - y_stored)
}
