#!/usr/bin/env python3
"""
Quick health check for a training run.

Usage:
  ./analyze_run.py <run_name_or_path>
  ./analyze_run.py ppo_1783347264
  ./analyze_run.py models/ppo_1783347264

Prints Q1..Q4 trajectory for the metrics that actually distinguish "learning"
from "collapsing", and flags concerning patterns.

Originally generated by Claude Code Opus 4.7 xHigh, then verified and
modified by the authors.
"""

import sys
from pathlib import Path

import numpy as np
from tensorboard.backend.event_processing import event_accumulator

MODELS_DIR = Path(__file__).resolve().parent / "models"

# tag -> (short label, "higher is better" | "lower is better" | None)
METRICS = [
    ("rewards/coverage",         "train_cov",     "higher"),
    ("rewards/eval_coverage",    "eval_cov",      "higher"),
    ("rewards/rewards",          "train_rew",     "higher"),
    ("rewards/eval_rewards",     "eval_rew",      "higher"),
    ("losses/entropy",           "entropy",       None),
    ("losses/approx_kl",         "approx_kl",     None),
    ("losses/clipfrac",          "clipfrac",      None),
    ("losses/value_loss",        "value_loss",    "lower"),
    ("losses/explained_variance","explained_var", "higher"),
    ("diag/gauss_final_layer_norm", "gauss_final_norm", None),
    ("sensitivity/means",        "sens_means",    "higher"),
    ("sensitivity/logstds",      "sens_logstds",  "higher"),
    ("sensitivity/weights",      "sens_weights",  "higher"),
    ("charts/learning_rate",     "lr",            None),
]


def resolve(arg: str) -> Path:
    p = Path(arg)
    if p.is_dir():
        return p
    p = MODELS_DIR / arg
    if p.is_dir():
        return p
    sys.exit(f"run not found: {arg}")


def load(run_path: Path):
    ea = event_accumulator.EventAccumulator(str(run_path), size_guidance={"scalars": 0})
    ea.Reload()
    return ea


def series(ea, tag):
    if tag not in ea.Tags()["scalars"]:
        return None
    ev = ea.Scalars(tag)
    return np.array([e.value for e in ev])


def quartiles(v):
    n = len(v)
    return [
        float(v[: n // 4].mean()),
        float(v[n // 4 : n // 2].mean()),
        float(v[n // 2 : 3 * n // 4].mean()),
        float(v[3 * n // 4 :].mean()),
    ]


def trend_arrow(q1, q4, direction):
    if direction is None:
        return "→" if abs(q4 - q1) / (abs(q1) + 1e-9) < 0.1 else ("↑" if q4 > q1 else "↓")
    good = (direction == "higher" and q4 > q1) or (direction == "lower" and q4 < q1)
    return "✓↑" if good and q4 > q1 else "✓↓" if good else ("✗↑" if q4 > q1 else "✗↓")


def main(arg: str):
    path = resolve(arg)
    ea = load(path)
    tags = ea.Tags()["scalars"]

    # Grab metrics we can find
    data = {}
    for tag, label, direction in METRICS:
        v = series(ea, tag)
        if v is None or len(v) < 4:
            continue
        data[label] = (v, direction)

    if not data:
        sys.exit("no known scalars found")

    n_iters = max(len(v) for v, _ in data.values())
    print(f"\n=== run: {path.name}  ({n_iters} iters) ===\n")

    # --- Quartile table ---
    print(f"  {'metric':<18s} {'Q1':>10s} {'Q2':>10s} {'Q3':>10s} {'Q4':>10s}   trend")
    print(f"  {'-'*18} {'-'*10} {'-'*10} {'-'*10} {'-'*10}   {'-'*5}")
    for tag, label, direction in METRICS:
        if label not in data:
            continue
        v, _ = data[label]
        q = quartiles(v)
        arrow = trend_arrow(q[0], q[3], direction)
        print(f"  {label:<18s} {q[0]:>10.4f} {q[1]:>10.4f} {q[2]:>10.4f} {q[3]:>10.4f}   {arrow}")

    print()

    # --- Best rolling window for eval_cov ---
    if "eval_cov" in data:
        ec, _ = data["eval_cov"]
        w = min(10, max(1, len(ec) // 20))
        if len(ec) >= w:
            rm = np.convolve(ec, np.ones(w) / w, mode="valid")
            best_i = int(np.argmax(rm))
            worst_i = int(np.argmin(rm))
            print(f"  eval_cov rolling-{w} best  = {rm[best_i]:.2f} at iters {best_i}..{best_i+w-1}")
            print(f"  eval_cov rolling-{w} worst = {rm[worst_i]:.2f} at iters {worst_i}..{worst_i+w-1}")
            print(f"  eval_cov last 10% mean  = {ec[-max(1,len(ec)//10):].mean():.2f}")

    # --- Correlations ---
    if "train_cov" in data and "eval_cov" in data:
        rc, _ = data["train_cov"]
        ec, _ = data["eval_cov"]
        n = min(len(rc), len(ec))
        if n > 5:
            r = float(np.corrcoef(rc[:n], ec[:n])[0, 1])
            print(f"  corr(train_cov, eval_cov)   = {r:+.3f}"
                  + ("   ⚠ near zero — train and eval decoupled" if abs(r) < 0.15 else ""))

    if "entropy" in data and "eval_cov" in data:
        ent, _ = data["entropy"]
        ec, _ = data["eval_cov"]
        n = min(len(ent), len(ec))
        if n > 5:
            r = float(np.corrcoef(ent[:n], ec[:n])[0, 1])
            print(f"  corr(entropy,  eval_cov)    = {r:+.3f}"
                  + ("   ⚠ negative — entropy inflation hurting eval" if r < -0.2 else ""))

    # --- Flags ---
    flags = []

    if "entropy" in data:
        ent, _ = data["entropy"]
        q1, q4 = ent[: len(ent) // 4].mean(), ent[3 * len(ent) // 4 :].mean()
        if q4 > q1 * 1.10:
            flags.append(f"entropy rose {q1:.1f} → {q4:.1f} (+{(q4/q1-1)*100:.0f}%). "
                         "policy noise inflating — lower ent_coef or cap the exploration stds.")

    if "lr" in data:
        lr, _ = data["lr"]
        if lr[-1] < 0.1 * lr[0]:
            flags.append(f"LR annealed from {lr[0]:.2e} to {lr[-1]:.2e}. "
                         "the last iters did almost no learning.")

    if "sens_logstds" in data:
        sl, _ = data["sens_logstds"]
        if sl[-max(1, len(sl)//4):].mean() < 5e-4:
            flags.append("sens/logstds ≈ 0 — component widths are input-invariant. "
                         "check the sigmoid squash in gmm.py:72.")

    if "sens_means" in data:
        sm, _ = data["sens_means"]
        end = sm[-max(1, len(sm)//4):].mean()
        if end < 5e-3:
            flags.append(f"sens/means ≈ {end:.4f} — mean policy barely responds to obs.")

    if "train_cov" in data and "eval_cov" in data:
        rc, _ = data["train_cov"]
        ec, _ = data["eval_cov"]
        # last 25% vs first 25%
        rc_delta = rc[3*len(rc)//4:].mean() - rc[:len(rc)//4].mean()
        ec_delta = ec[3*len(ec)//4:].mean() - ec[:len(ec)//4].mean()
        if rc_delta > 1.0 and ec_delta < -1.0:
            flags.append(f"train_cov rose {rc_delta:+.1f} but eval_cov fell {ec_delta:+.1f}. "
                         "classic overfit-to-stochastic-exploration collapse.")

    if "approx_kl" in data:
        kl, _ = data["approx_kl"]
        if kl[-max(1, len(kl)//4):].mean() < 5e-4:
            flags.append(f"approx_kl ≈ {kl[-max(1, len(kl)//4):].mean():.4f} — policy is barely updating. "
                         "reward variance may be too low.")

    if "explained_var" in data:
        ev, _ = data["explained_var"]
        if ev[-max(1, len(ev)//4):].mean() < 0.2:
            flags.append("explained_variance < 0.2 — critic is not fitting returns.")

    if flags:
        print("\n  === concerns ===")
        for f in flags:
            print(f"  - {f}")
    else:
        print("\n  no critical flags. run looks structurally healthy.")

    print()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: analyze_run.py <run_name_or_path>")
    main(sys.argv[1])
