#!/bin/bash
# Wall-clock comparison of unpruned vs learned pruning across move budgets and
# clutter levels.
#
# Timing methodology:
#   1. Timer starts when the child prints MARKER (Python interpreter announcement).
#      This excludes Rust binary startup + PyO3 init + Python launch, which are
#      constant per invocation and would otherwise skew short-episode runs.
#   2. A calibration run (`--episodes 1 --num-moves 1`) measures post-marker
#      startup cost (model load, sim spinup, initial FOV paint). Subtracted
#      from each real row's total before dividing by EPISODES.
#   Net result: per-episode time reflects steady-state exploration work only.
#
# Usage:
#   ./bench_wallclock.sh --load <checkpoint>
#
# Environment overrides:
#   EPISODES=25                     episodes per (arm, budget, clutter) triple
#   BUDGETS="100 1000 2000"         space-separated move budgets to sweep
#   CLUTTERS="mid high spicy"       space-separated clutter levels to sweep
#
# Any additional flags after --load pass through to the trainer. Flags that
# the script sets itself are stripped from the passthrough so they don't
# collide (see STRIP_BOOL / STRIP_VAL below).
#
# Output prints a summary table and writes it to bench_wallclock_<ts>.log.
# 
# Originally generated by Claude Code Opus 4.7 xHigh, then verified and
# modified by the authors.

set -euo pipefail

EPISODES="${EPISODES:-25}"
BUDGETS="${BUDGETS:-100 1000 2000}"
CLUTTERS="${CLUTTERS:-mid high spicy}"

OUT="results/bench_wallclock_$(date +%Y%m%d_%H%M%S).log"
BIN=./target/release/trainer

# Substring the child must print for the timer to start. Matched with bash
# glob-like `==` so anchoring isn't required.
MARKER="[PYINFO] Using python interpreter"

# --- strip flags we set ourselves so passthrough can't collide ------------
# Ported from run_experiments.sh. If the user passes any of these on the
# command line, they'd end up duplicated in each trainer invocation (leading
# to argparse errors or, worse, silent overrides). Strip them and re-emit
# the ones we control.
STRIP_BOOL="--test --no-prune --random"
STRIP_VAL="--num-moves --episodes --num-eval --clutter"

FILTERED=()
skip_next=0
for a in "$@"; do
    if [ "$skip_next" = "1" ]; then
        skip_next=0
        continue
    fi

    drop=0
    for f in $STRIP_BOOL; do
        [ "$a" = "$f" ] && drop=1
    done
    for f in $STRIP_VAL; do
        if [ "$a" = "$f" ]; then drop=1; skip_next=1; fi
    done
    for f in $STRIP_VAL; do
        case "$a" in "$f"=*) drop=1 ;; esac
    done

    if [ "$drop" = "0" ]; then
        FILTERED+=("$a")
    fi
done

# `${FILTERED[@]+"${FILTERED[@]}"}` guards against `set -u` on empty arrays
# (bash treats an unset [@] expansion as "unbound" under strict mode).
ARGS=("${FILTERED[@]+"${FILTERED[@]}"}")

# --- build & preflight -----------------------------------------------------
cargo build --release --bin trainer

echo -e "\e[92mwall-clock bench: $EPISODES episodes per (arm, budget, clutter)\e[0m"
echo -e "\e[92mbudgets:  $BUDGETS\e[0m"
echo -e "\e[92mclutters: $CLUTTERS\e[0m"

ROWS=$(mktemp)
trap 'rm -f "$ROWS"' EXIT

# Run $BIN with given args; time from when MARKER prints to process exit.
# stdbuf forces line-buffered child output so `read` sees each line as it
# emerges rather than in 4kB blocks (otherwise the marker timestamp lags by
# whatever's needed to fill the buffer). Merges stderr into stdout so the
# marker is found regardless of which stream it lands on.
# On stdout: elapsed seconds (float, 6-digit precision).
# Exits the whole script if MARKER never appears (that's a signal something
# fundamental is broken; better to fail loud than silently mis-time).
run_timed() {
    local t_start=""
    local t_end
    while IFS= read -r line; do
        if [ -z "$t_start" ] && [[ "$line" == *"$MARKER"* ]]; then
            t_start=$(date +%s.%N)
        fi
    done < <(stdbuf -oL -eL "$BIN" "$@" 2>&1)
    t_end=$(date +%s.%N)

    if [ -z "$t_start" ]; then
        echo "error: MARKER '$MARKER' not found in child output" >&2
        exit 1
    fi
    awk "BEGIN{printf \"%.6f\", $t_end - $t_start}"
}

# --- calibration: post-marker startup cost -------------------------------
# Per-arm because startup is arm-dependent:
#   - no_prune skips the actor entirely, so it pays only model load + sim spinup.
#   - learned runs the actor on the first step, which triggers `torch.compile`
#     on `agent.tform`. That compile is a one-time cost per invocation and
#     dwarfs everything else. Calibrating only with --no-prune would leave
#     the compile cost unamortized inside every learned row (i.e., we'd
#     under-subtract and per-episode learned times would look inflated).
# Clutter-independent (both terms are load/compile costs), so one calibration
# per arm at the first sweep clutter is enough.
CAL_CLUTTER=$(echo "$CLUTTERS" | awk '{print $1}')

echo
echo -e "\e[90mcalibrating post-marker startup (clutter=$CAL_CLUTTER)...\e[0m"
STARTUP_NP=$(run_timed \
    --test --no-prune \
    --num-moves 1 --episodes 1 --num-eval 1 \
    --clutter "$CAL_CLUTTER" \
    ${ARGS[@]+"${ARGS[@]}"})
printf "  no_prune startup: %.2fs\n" "$STARTUP_NP"

STARTUP_LN=$(run_timed \
    --test \
    --num-moves 1 --episodes 1 --num-eval 1 \
    --clutter "$CAL_CLUTTER" \
    ${ARGS[@]+"${ARGS[@]}"})
printf "  learned  startup: %.2fs  (delta vs no_prune ≈ torch.compile cost: %.2fs)\n" \
    "$STARTUP_LN" \
    "$(awk -v a="$STARTUP_LN" -v b="$STARTUP_NP" 'BEGIN{printf "%.2f", a-b}')"

# --- real runs ------------------------------------------------------------
for BUDGET in $BUDGETS; do
    for CLUTTER in $CLUTTERS; do
        for ARM in no_prune learned; do
            case "$ARM" in
                no_prune) EXTRA="--no-prune" ;;
                learned)  EXTRA=""           ;;
            esac

            echo
            echo -e "\e[92m--- $ARM, $BUDGET moves, clutter=$CLUTTER ---\e[0m"

            TOTAL_RAW=$(run_timed \
                --test $EXTRA \
                --num-moves "$BUDGET" \
                --episodes "$EPISODES" \
                --num-eval 1 \
                --clutter "$CLUTTER" \
                ${ARGS[@]+"${ARGS[@]}"})

            # Pick the arm-matched startup baseline: no_prune skips the actor
            # so it never triggers torch.compile; learned pays that on first
            # forward. Startup fires ONCE per invocation, so we subtract it
            # once from TOTAL_RAW (not once per episode) before dividing.
            if [ "$ARM" = "no_prune" ]; then STARTUP=$STARTUP_NP; else STARTUP=$STARTUP_LN; fi

            # Subtract startup; clamp at 0 in the degenerate case where startup
            # exceeds the real run (means EPISODES is far too small — bump it).
            TOTAL=$(awk -v t="$TOTAL_RAW" -v s="$STARTUP" \
                'BEGIN{d=t-s; if(d<0){d=0}; printf "%.2f", d}')
            PER_EP=$(awk -v t="$TOTAL" -v n="$EPISODES" \
                'BEGIN{printf "%.3f", t/n}')

            printf "raw: %ss, minus startup: %ss (%ss/episode)\n" \
                "$TOTAL_RAW" "$TOTAL" "$PER_EP"
            echo "$ARM $BUDGET $CLUTTER $TOTAL $PER_EP" >> "$ROWS"
        done
    done
done

# --- summary --------------------------------------------------------------
# Per (budget, clutter) pair: emit both arms adjacently with the learned/no_prune
# per-episode ratio in the last column.
echo
echo -e "\e[92m=== SUMMARY ===\e[0m"

fmt='%-10s %-10s %-10s %-14s %-14s %-12s\n'
{
    printf "startup baselines (subtracted per arm): no_prune=%.2fs, learned=%.2fs\n\n" \
        "$STARTUP_NP" "$STARTUP_LN"
    printf "$fmt" "arm" "budget" "clutter" "total (s)" "per-ep (s)" "vs no_prune"
    for BUDGET in $BUDGETS; do
        for CLUTTER in $CLUTTERS; do
            NP=$(awk -v b="$BUDGET" -v c="$CLUTTER" \
                '$1=="no_prune" && $2==b && $3==c {print $5}' "$ROWS")
            for ARM in no_prune learned; do
                read _ _ _ TOTAL PER_EP < <(awk -v a="$ARM" -v b="$BUDGET" -v c="$CLUTTER" \
                    '$1==a && $2==b && $3==c {print $0}' "$ROWS")
                if [ "$ARM" = "no_prune" ]; then
                    RATIO="1.00x"
                else
                    RATIO=$(awk -v x="$PER_EP" -v y="$NP" 'BEGIN{printf "%.2fx", x/y}')
                fi
                printf "$fmt" "$ARM" "$BUDGET" "$CLUTTER" "$TOTAL" "$PER_EP" "$RATIO"
            done
        done
    done
} | tee "$OUT"

echo
echo -e "\e[92msaved: $OUT\e[0m"
