#!/usr/bin/env python3
"""
Grouped bar chart of coverage change vs no-pruning baseline (percentage points).

Companion to plot_grouped_coverage.py. Instead of raw mean coverage per arm,
each bar shows arm_mean - no_prune_mean directly — so if no_prune covers 29% of
the map and random covers 22%, random's bar reads -7 (pp). no_prune is the
invisible zero line, random/learned live ± around it, and each group's x-tick
label carries no_prune's absolute coverage as the anchor.

Units are percentage POINTS, not percent (that's `plot_ratio_coverage.py`).

Error bars are bootstrap 16/84 percentiles of the per-resample difference.
Episodes across arms are different seeds/maps, so we resample each arm
independently (unpaired) — pairing would be a fabrication.

Originally generated by Claude Code Opus 4.7 xHigh, then verified and
modified by the authors.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import font_manager as fm
from matplotlib.colors import to_rgba


# --- style block (mirrors plot_grouped_coverage.py) ------------------------

LMR_FONT_PATHS = [
    Path(__file__).parent / "lmroman10-regular.otf",
    Path.home() / ".fonts/lmroman10-regular.otf",
    Path("/usr/share/fonts/OTF/lmroman10-regular.otf"),
    Path("/usr/share/fonts/opentype/lmodern/lmroman10-regular.otf"),
    Path("/usr/share/fonts/truetype/lmodern/lmroman10-regular.otf"),
]
for _p in LMR_FONT_PATHS:
    if _p.exists():
        fm.fontManager.addfont(str(_p))
        plt.rcParams["font.family"] = "LMRoman10"
        break
else:
    plt.rcParams["font.family"] = "serif"

FONT_SIZE_LABEL = 10
FONT_SIZE_TICK  = 10
LABELPAD        = 15
BAR_ALPHA       = 0.3
BAR_EDGE_LW     = 1
BAR_PITCH       = 0.25
BAR_GAP         = 0.03
ERROR_LW        = 1
ERROR_CAPSIZE   = 4
GRID_ALPHA      = 0.3
BG_COLOR        = "white"
ZERO_LINE_LW    = 1
ZERO_LINE_COL   = "#333"

# --- what to plot ----------------------------------------------------------

GROUPS = [
    # ("results/experiment_20260811_191937", "Sparse Clutter (100 moves)"),
    ("results/experiment_20260811_145121", "Sparse Clutter\n(100 moves)"),
    ("results/experiment_20260811_143034", "Moderate Clutter\n(100 moves)"),
    ("results/experiment_20260811_141417", "Dense Clutter\n(100 moves)"),
    ("results/experiment_20260811_125437", "Dense Clutter\n(1000 moves)"),
    ("results/experiment_20260811_212822", "Dense Clutter\n(2000 moves)")
]

# no_prune is the baseline (rendered as x-tick annotation, no bar drawn).
COMPARE_ARMS = ["random", "learned"]
ARM_LABELS = {
    "random":  "Random pruning",
    "learned": "Learned pruning (ours)",
}
ARM_COLORS = {
    "random":  "darkorange",
    "learned": "forestgreen",
}

BOOTSTRAP_N = 10_000
BOOTSTRAP_SEED = 0

OUTPUT_PDF = "coverage_relative_bars.pdf"
OUTPUT_PNG = "coverage_relative_bars.png"
Y_LABEL    = "Exploration Progress vs.\nUnpruned RRT (pp difference)"

FIG_HEIGHT_PX = 310  # a bit taller than the raw plot: the two-line x-ticks eat space
FIG_WIDTH_PX  = int(FIG_HEIGHT_PX * 2.75)

# ---------------------------------------------------------------------------

STAT_RE = re.compile(
    r"EVAL_STATS\s+coverage=([\d.eE+-]+)"
    r"(?:\s+initial_coverage=([\d.eE+-]+))?"
)


def parse_coverages(log_path: Path) -> np.ndarray:
    if not log_path.exists():
        return np.array([])
    vals = []
    for line in log_path.read_text().splitlines():
        m = STAT_RE.search(line)
        if m:
            cov = float(m.group(1))
            init = float(m.group(2)) if m.group(2) is not None else 0.0
            vals.append(cov - init)
    return np.array(vals, dtype=float)


def bootstrap_delta(
    arm: np.ndarray, base: np.ndarray, n: int, rng: np.random.Generator
) -> tuple[float, float, float]:
    """Percentage-point difference (arm - base) with bootstrap CI.

    Returns (point_estimate, p16, p84). Point estimate uses raw sample means;
    the CI comes from `n` independent unpaired resamples of both arms.
    """
    if len(arm) == 0 or len(base) == 0:
        return (np.nan, np.nan, np.nan)
    a_idx = rng.integers(0, len(arm), size=(n, len(arm)))
    b_idx = rng.integers(0, len(base), size=(n, len(base)))
    a_means = arm[a_idx].mean(axis=1)
    b_means = base[b_idx].mean(axis=1)
    deltas = a_means - b_means
    point = arm.mean() - base.mean()
    return point, np.percentile(deltas, 16), np.percentile(deltas, 84)


def main() -> int:
    n_groups = len(GROUPS)
    n_arms = len(COMPARE_ARMS)
    rng = np.random.default_rng(BOOTSTRAP_SEED)

    points = np.zeros((n_groups, n_arms))
    lo = np.zeros((n_groups, n_arms))
    hi = np.zeros((n_groups, n_arms))
    baselines = np.full(n_groups, np.nan)
    ns_base = np.zeros(n_groups, dtype=int)
    ns_arm = np.zeros((n_groups, n_arms), dtype=int)

    for gi, (path, _label) in enumerate(GROUPS):
        base = parse_coverages(Path(path) / "eval_no_prune.log")
        ns_base[gi] = len(base)
        if len(base):
            baselines[gi] = base.mean()
        for ai, arm in enumerate(COMPARE_ARMS):
            covs = parse_coverages(Path(path) / f"eval_{arm}.log")
            ns_arm[gi, ai] = len(covs)
            p, l_, h_ = bootstrap_delta(covs, base, BOOTSTRAP_N, rng)
            points[gi, ai] = p
            lo[gi, ai] = l_
            hi[gi, ai] = h_

    print("sample sizes and no_prune baseline (rows = groups):")
    for gi, (_, label) in enumerate(GROUPS):
        clean = label.replace("\n", " ")
        base_str = f"{baselines[gi]:.2f}%" if not np.isnan(baselines[gi]) else "—"
        arms_str = "  ".join(f"{a}={ns_arm[gi, ai]}" for ai, a in enumerate(COMPARE_ARMS))
        print(f"  {clean:35s}  no_prune={ns_base[gi]} ({base_str})  {arms_str}")

    # --- plot ---
    fig, ax = plt.subplots(figsize=(FIG_WIDTH_PX/100, FIG_HEIGHT_PX/100), dpi=100)
    fig.patch.set_facecolor(BG_COLOR)

    x = np.arange(n_groups)
    bar_w = BAR_PITCH - BAR_GAP

    # Zero reference line = no_prune baseline. Draws the visual anchor for
    # positive/negative bars and makes the sign of each delta unmissable.
    ax.axhline(0.0, color=ZERO_LINE_COL, linewidth=ZERO_LINE_LW, zorder=1)

    for ai, arm in enumerate(COMPARE_ARMS):
        offset = (ai - (n_arms - 1) / 2) * BAR_PITCH
        color = ARM_COLORS[arm]
        face = to_rgba(color, alpha=BAR_ALPHA)
        # Asymmetric error bars: matplotlib wants [[below], [above]] as
        # positive lengths from the bar tip, not absolute coordinates.
        yerr = np.vstack([
            np.maximum(0, points[:, ai] - lo[:, ai]),
            np.maximum(0, hi[:, ai] - points[:, ai]),
        ])
        ax.bar(
            x + offset,
            points[:, ai],
            bar_w,
            yerr=yerr,
            capsize=ERROR_CAPSIZE,
            color=face,
            edgecolor=color,
            linewidth=BAR_EDGE_LW,
            label=ARM_LABELS[arm],
            error_kw={"linewidth": ERROR_LW, "ecolor": color},
        )

        print(points[:, ai] - yerr, arm)

    # Fold no_prune's absolute coverage into each x-tick label — that's the
    # anchor the reader needs to interpret "% change vs baseline".
    xtick_labels = [
        f"{lbl}\nUnpruned @ {b:.2f}%\nn = {n}" if not np.isnan(b) else lbl
        for (_, lbl), b, n in zip(GROUPS, baselines, ns_base)
    ]
    ax.set_xticks(x)
    ax.set_xticklabels(xtick_labels, fontsize=FONT_SIZE_TICK)
    ax.set_ylabel(Y_LABEL, fontsize=FONT_SIZE_LABEL, labelpad=LABELPAD)
    ax.tick_params(labelsize=FONT_SIZE_TICK)
    ax.grid(True, axis="y", alpha=GRID_ALPHA)
    ax.set_axisbelow(True)
    ax.legend(loc="upper left", fontsize=FONT_SIZE_TICK, frameon=True)

    plt.tight_layout()
    plt.savefig(OUTPUT_PDF, dpi=100, bbox_inches="tight", pad_inches=0.05, format="pdf")
    plt.savefig(OUTPUT_PNG, dpi=150, bbox_inches="tight")
    print(f"saved {OUTPUT_PDF} and {OUTPUT_PNG}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
