#!/usr/bin/env python3
"""
Heatmap of per-episode wall-clock speedup (unpruned / learned) across
budget × clutter. Companion to the coverage figures.

Cells show speedup so bigger reads as better ("learned is 2× faster than
unpruned"). Values are the reciprocal of bench_wallclock.sh's `vs no_prune`
column, which reports the learned/unpruned ratio — the script does the
inversion internally so the pasted RATIOS array can stay verbatim.

Colors are mapped in log2(speedup) space so speedup=2 (2× faster) and
speedup=0.5 (2× slower) are visually equidistant from parity — the natural
symmetry for multiplicative comparisons.

Originally generated by Claude Code Opus 4.7 xHigh, then verified and
modified by the authors.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import font_manager as fm
from matplotlib.colors import TwoSlopeNorm

# plt.rcParams['text.usetex'] = True


# --- style block (mirrors plot_grouped_coverage.py) ------------------------

LMR_FONT_PATHS = [
    Path(__file__).parent / "lmroman10-regular.otf",
    Path.home() / ".fonts/lmroman10-regular.otf",
    Path("/usr/share/fonts/OTF/lmroman10-regular.otf"),
    Path("/usr/share/fonts/opentype/lmodern/lmroman10-regular.otf"),
    Path("/usr/share/fonts/truetype/lmodern/lmroman10-regular.otf"),
]
for _p in LMR_FONT_PATHS:
    if _p.exists():
        fm.fontManager.addfont(str(_p))
        
        # 1. Set the regular text font family
        plt.rcParams["font.family"] = "LMRoman10"
        
        # 2. Configure Mathtext to use your custom font definitions
        plt.rcParams["mathtext.fontset"] = "custom"
        plt.rcParams["mathtext.rm"] = "LMRoman10"
        plt.rcParams["mathtext.it"] = "LMRoman10:italic"
        plt.rcParams["mathtext.bf"] = "LMRoman10:bold"
        break
else:
    plt.rcParams["font.family"] = "serif"
    plt.rcParams["mathtext.fontset"] = "cm"

FONT_SIZE_LABEL = 10
FONT_SIZE_TICK  = 10
FONT_SIZE_CELL  = 11
LABELPAD        = 20    # breathing room around axis + colorbar labels
BG_COLOR        = "white"

# --- data ------------------------------------------------------------------
# Paste from bench_wallclock.sh SUMMARY output. Row order = CLUTTERS,
# column order = BUDGETS. Cell = learned/no_prune per-episode ratio.
#
# Ratio < 1 → learned faster; ratio > 1 → learned slower; ratio = 1 → parity.

CLUTTERS       = ["mid", "high", "spicy"]
CLUTTER_LABELS = ["Sparse", "Moderate", "Dense"]
BUDGETS        = [100, 1000, 2000]

RATIOS = np.array([
    # 100     1000    2000
    [1.63,   1.47,   1.24],   # mid
    [0.99,   0.87,   0.52],   # high
    [1.21,   0.58,   0.50],   # spicy
])

# Invert so cells read as speedup (larger = learned is faster). Everything
# below (color mapping, cell labels, colorbar) operates on speedups.
SPEEDUPS = 1.0 / RATIOS

# --- plot ------------------------------------------------------------------

OUTPUT_PDF = "wallclock_heatmap.pdf"
OUTPUT_PNG = "wallclock_heatmap.png"

# Diverging colormap: low input → red, high input → blue. Since we feed
# log2(speedup) into it, positive log2 (speedup>1 = learned faster) → blue,
# negative (learned slower) → red. Blue = good, red = bad — the direction
# the reader expects given cells are labeled as speedups.
CMAP_NAME = "RdBu"

# Symmetric limits in log2 space. Clamp to at least 1.0 so the color scale
# always spans ≥ [0.5×, 2×], keeping the perceptual scale stable if you
# swap in tighter data later.
log_speedups = np.log2(SPEEDUPS)
LIMIT = max(abs(log_speedups).max(), 1.0)
norm = TwoSlopeNorm(vmin=-LIMIT, vcenter=0.0, vmax=LIMIT)
cmap = plt.get_cmap(CMAP_NAME)

# Aspect: modest square-ish figure. Coverage figure is wide (~715×260); this
# is a companion figure showing a 3×3 grid, so it wants to be closer to
# square than to the coverage aspect. Adjust FIG_WIDTH_PX to fit column.
FIG_HEIGHT_PX = 370
FIG_WIDTH_PX  = 800

fig, ax = plt.subplots(figsize=(FIG_WIDTH_PX/135, FIG_HEIGHT_PX/135), dpi=100)
fig.patch.set_facecolor(BG_COLOR)

# aspect="equal" keeps cells square regardless of figure/axes shape.
# aspect="auto" would stretch them to fill the axes, which produces
# rectangular cells whenever the axes rectangle isn't itself square.
im = ax.imshow(log_speedups, cmap=cmap, norm=norm, aspect="equal")

# In-cell numeric label. Switch text color to white when the cell background
# is dark (|log2 speedup| > TEXT_DARK_THRESH), else black. Threshold picked so
# cells outside roughly [0.7×, 1.4×] use white text.
TEXT_DARK_THRESH = 0.5
for i in range(len(CLUTTERS)):
    for j in range(len(BUDGETS)):
        s = SPEEDUPS[i, j]
        text_color = "white" if abs(log_speedups[i, j]) > TEXT_DARK_THRESH else "black"
        ax.text(j, i, f"{s:.2f}×",
                ha="center", va="center",
                fontsize=FONT_SIZE_CELL, color=text_color)

ax.set_xticks(np.arange(len(BUDGETS)))
ax.set_xticklabels([str(b) for b in BUDGETS], fontsize=FONT_SIZE_TICK)
ax.set_yticks(np.arange(len(CLUTTERS)))
# Rotated vertical so the clutter labels don't push the heatmap right
# and eat horizontal space; `va="center"` keeps them aligned with the row.
ax.set_yticklabels(CLUTTER_LABELS, fontsize=FONT_SIZE_TICK,
                   rotation="vertical", va="center")
ax.set_xlabel("Exploration Horizon (moves)", fontsize=FONT_SIZE_LABEL, labelpad=LABELPAD-10)
ax.set_ylabel("Environment Complexity", fontsize=FONT_SIZE_LABEL, labelpad=LABELPAD)

# Colorbar. Only three ticks (endpoints + parity) — the intermediate ticks
# add margin noise without helping interpretation. Labels shown as
# multiplicative ratios ("0.50×") rather than log2 values.
cbar_ticks_log = np.array([-LIMIT, 0.0, LIMIT])
cbar_ticks_lbl = [f"{2 ** t:.2f}×" for t in cbar_ticks_log]
cbar = plt.colorbar(im, ax=ax, shrink=0.85, pad=0.04)
cbar.set_ticks(cbar_ticks_log)
cbar.set_ticklabels(cbar_ticks_lbl)
cbar.set_label("Wall-clock speedup vs unpruned",
               fontsize=FONT_SIZE_LABEL, labelpad=LABELPAD)
cbar.ax.tick_params(labelsize=FONT_SIZE_TICK)

# Remove the default axis frame around the heatmap so cells look cleaner.
for spine in ax.spines.values():
    spine.set_visible(False)
ax.tick_params(top=False, bottom=False, left=False, right=False)

plt.tight_layout()
plt.savefig(OUTPUT_PDF, dpi=100, bbox_inches="tight", pad_inches=0.05, format="pdf")
plt.savefig(OUTPUT_PNG, dpi=150, bbox_inches="tight")
print(f"saved {OUTPUT_PDF} and {OUTPUT_PNG}")
