#!/usr/bin/env python3
"""
Grouped bar chart of coverage mean±std across experiments and pruning arms.

Styled to match the paper's training-curve figures: Computer Modern Serif
font, steelblue/darkorange/forestgreen palette, subtle grid at alpha=0.3,
matching label/tick font sizes, PDF output. Edit the GROUPS list and the
STYLE block below.

Originally generated by Claude Code Opus 4.7 xHigh, then verified and
modified by the authors.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import font_manager as fm
from matplotlib.colors import to_rgba


# --- style block (match paper's line charts) -------------------------------

# Prefer Latin Modern Roman (a modernized Computer Modern with better
# Unicode coverage — visually indistinguishable from CMU in a matplotlib
# figure). System locations we try, in order. If none exist, falls back to
# matplotlib's default serif.
#   Debian/Ubuntu: sudo apt install lmodern
#   Arch:          sudo pacman -S tex-gyre-fonts   (or otf-latin-modern via AUR)
LMR_FONT_PATHS = [
    Path(__file__).parent / "lmroman10-regular.otf",
    Path.home() / ".fonts/lmroman10-regular.otf",
    Path("/usr/share/fonts/OTF/lmroman10-regular.otf"),
    Path("/usr/share/fonts/opentype/lmodern/lmroman10-regular.otf"),
    Path("/usr/share/fonts/truetype/lmodern/lmroman10-regular.otf"),
]
for _p in LMR_FONT_PATHS:
    if _p.exists():
        fm.fontManager.addfont(str(_p))
        # `LMRoman10` is the family name matplotlib registers for
        # lmroman10-regular.otf on Arch (visible via `fc-list`). Some
        # distros register the family as "Latin Modern Roman" instead —
        # inspect fm.fontManager.ttflist and swap this if needed.
        plt.rcParams["font.family"] = "LMRoman10"
        break
else:
    plt.rcParams["font.family"] = "serif"

FONT_SIZE_LABEL = 12
FONT_SIZE_TICK  = 10
LABELPAD        = 6
BAR_ALPHA       = 0.3   # face fill: matches the alpha=0.3 confidence bands on the paper's line charts
BAR_EDGE_LW     = 1   # bar outline in the solid arm color
BAR_PITCH       = 0.25  # distance between adjacent bar centers within a group
BAR_GAP         = 0.03  # visible spacing between adjacent bars (subtracts from bar width)
ERROR_LW        = 1     # matches the paper's linewidth for the actual mean line
ERROR_CAPSIZE   = 4
GRID_ALPHA      = 0.3
BG_COLOR        = "white"

# --- what to plot ----------------------------------------------------------

GROUPS = [
    ("results/experiment_20260811_191937", "Sparse Clutter (100 moves)"),
    ("results/experiment_20260811_145121", "Moderate Clutter (100 moves)"),
    ("results/experiment_20260811_143034", "Dense Clutter (100 moves)"),
    ("results/experiment_20260811_141417", "Saturated Clutter (100 moves)"),
    ("results/experiment_20260811_125437", "Saturated Clutter (1000 moves)"),
    ("results/experiment_20260811_212822", "Saturated Clutter (2000 moves)")
]

ARMS = ["no_prune", "random", "learned"]
ARM_LABELS = {
    "no_prune": "No Pruning",
    "random":   "Random",
    "learned":  "Learned",
}
# Paper's palette for the three per-panel line series.
ARM_COLORS = {
    "no_prune": "steelblue",
    "random":   "darkorange",
    "learned":  "forestgreen",
}

OUTPUT_PDF = "coverage_grouped_bars.pdf"
OUTPUT_PNG = "coverage_grouped_bars.png"  # quick preview
Y_LABEL    = "Percent Coverage"

# Aspect ratio: paper's three-panel row is 11:2 (very wide). A single grouped
# bar chart looks awkward that wide, so use ~2.75:1 which is roughly one panel
# from the paper's row. Change if you want it narrower/wider.
FIG_HEIGHT_PX = 500
FIG_WIDTH_PX  = int(FIG_HEIGHT_PX * 3)  # ~715px

# ---------------------------------------------------------------------------

# Subtract the starting FOV area from the final coverage so bars report
# *exploration gain* rather than "total painted pixels" (which includes the
# initial-visibility disc). `initial_coverage=` was added to EVAL_STATS on
# 2026-08-03; older logs won't have it — the regex makes it optional and we
# subtract 0 in that case.
STAT_RE = re.compile(
    r"EVAL_STATS\s+coverage=([\d.eE+-]+)"
    r"(?:\s+initial_coverage=([\d.eE+-]+))?"
)


def parse_coverages(log_path: Path) -> np.ndarray:
    if not log_path.exists():
        return np.array([])
    vals = []
    for line in log_path.read_text().splitlines():
        m = STAT_RE.search(line)
        if m:
            cov = float(m.group(1))
            init = float(m.group(2)) if m.group(2) is not None else 0.0
            vals.append(cov - init)
    return np.array(vals, dtype=float)


def main() -> int:
    n_groups = len(GROUPS)
    n_arms = len(ARMS)
    means = np.zeros((n_groups, n_arms))
    stds  = np.zeros((n_groups, n_arms))
    ns    = np.zeros((n_groups, n_arms), dtype=int)

    for gi, (path, _label) in enumerate(GROUPS):
        for ai, arm in enumerate(ARMS):
            log = Path(path) / f"eval_{arm}.log"
            covs = parse_coverages(log)
            ns[gi, ai] = len(covs)
            if len(covs):
                means[gi, ai] = covs.mean()
                stds[gi, ai]  = covs.std(ddof=1) if len(covs) > 1 else 0.0
            else:
                print(f"[warn] no data in {log}", file=sys.stderr)

    print("sample sizes (rows = groups, cols = arms):")
    for gi, (_, label) in enumerate(GROUPS):
        print(f"  {label:45s}  " + "  ".join(f"{arm}={ns[gi, ai]}" for ai, arm in enumerate(ARMS)))

    # --- plot ---
    fig, ax = plt.subplots(figsize=(FIG_WIDTH_PX/100, FIG_HEIGHT_PX/100), dpi=100)
    fig.patch.set_facecolor(BG_COLOR)

    x = np.arange(n_groups)
    bar_w = BAR_PITCH - BAR_GAP   # visible bar width; gap sits between neighbors

    for ai, arm in enumerate(ARMS):
        # Center-space bars at multiples of BAR_PITCH (not bar_w) so shrinking
        # bar_w produces a visible gap instead of just narrower bars glued together.
        offset = (ai - (n_arms - 1) / 2) * BAR_PITCH
        color = ARM_COLORS[arm]
        # Fill alpha via RGBA on the face color so the outline (edgecolor)
        # stays fully opaque. Setting `alpha=` on the bar itself would
        # apply the same transparency to the edge, which we don't want.
        face = to_rgba(color, alpha=BAR_ALPHA)
        ax.bar(
            x + offset,
            means[:, ai],
            bar_w,
            yerr=stds[:, ai],
            capsize=ERROR_CAPSIZE,
            # Semi-transparent fill = paper's alpha=0.3 confidence band;
            # solid outline + error bar in the same color = paper's mean line.
            color=face,
            edgecolor=color,
            linewidth=BAR_EDGE_LW,
            label=ARM_LABELS[arm],
            error_kw={"linewidth": ERROR_LW, "ecolor": color},
        )

    ax.set_xticks(x)
    ax.set_xticklabels([lbl for _, lbl in GROUPS], fontsize=FONT_SIZE_TICK)
    ax.set_ylabel(Y_LABEL, fontsize=FONT_SIZE_LABEL, labelpad=LABELPAD)
    ax.tick_params(labelsize=FONT_SIZE_TICK)
    ax.set_ylim(bottom=0)
    ax.grid(True, axis="y", alpha=GRID_ALPHA)
    ax.set_axisbelow(True)  # grid behind the bars, like the paper's lines
    ax.legend(loc="upper right", fontsize=FONT_SIZE_TICK, frameon=True)

    plt.tight_layout()
    plt.savefig(OUTPUT_PDF, dpi=100, bbox_inches="tight", pad_inches=0.05, format="pdf")
    plt.savefig(OUTPUT_PNG, dpi=150, bbox_inches="tight")
    print(f"saved {OUTPUT_PDF} and {OUTPUT_PNG}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
