#!/usr/bin/env python3
"""
Rank checkpoints in a run by eval coverage.

Usage:
  ./top_checkpoints.py <run_name_or_path> [top_n=10]
  ./top_checkpoints.py ppo_1783381671 20
  ./top_checkpoints.py --tag rewards/eval_rewards ppo_1783381671

Notes:
  - runner.py:save() names checkpoints ppo{global_step // 6400}.pt, so each
    checkpoint covers a 6400-global_step window. This script groups eval
    scalars by that window, takes the max in each window, then ranks.
  - Flags MISSING for checkpoints you already deleted, so you can copy the
    remaining ones somewhere safe without hunting them down manually.

Originally generated by Claude Code Opus 4.7 xHigh, then verified and
modified by the authors.
"""

import argparse
import sys
from pathlib import Path

from tensorboard.backend.event_processing import event_accumulator

MODELS_DIR = Path(__file__).resolve().parent / "models"
DEFAULT_STEPS_PER_CKPT = 6400  # matches runner.save()


def resolve(arg: str) -> Path:
    p = Path(arg)
    if p.is_dir():
        return p
    p = MODELS_DIR / arg
    if p.is_dir():
        return p
    sys.exit(f"run not found: {arg}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("run", help="run name (looks in models/) or full path")
    ap.add_argument("top_n", nargs="?", type=int, default=10)
    ap.add_argument("--tag", default="rewards/eval_coverage",
                    help="TB scalar tag to rank by")
    ap.add_argument("--steps-per-ckpt", type=int, default=DEFAULT_STEPS_PER_CKPT,
                    help="global_step window per checkpoint filename (matches runner.save)")
    ap.add_argument("--sort", choices=("value", "ckpt"), default="value",
                    help="sort by tag value (default) or checkpoint number")
    args = ap.parse_args()

    path = resolve(args.run)
    ea = event_accumulator.EventAccumulator(str(path), size_guidance={"scalars": 0})
    ea.Reload()

    if args.tag not in ea.Tags()["scalars"]:
        avail = ", ".join(t for t in ea.Tags()["scalars"] if "rewards" in t or "cov" in t)
        sys.exit(f"tag '{args.tag}' not in this run.\nAvailable reward/cov tags: {avail}")

    # Group scalars by their checkpoint window; keep the max value in each
    # window (a single ckpt file corresponds to whatever policy state existed
    # at the *end* of its window, so max-in-window is a decent proxy for
    # "best eval that ckpt could have produced").
    by_ckpt: dict[int, tuple[int, float]] = {}
    for ev in ea.Scalars(args.tag):
        ckpt = ev.step // args.steps_per_ckpt
        if ckpt not in by_ckpt or ev.value > by_ckpt[ckpt][1]:
            by_ckpt[ckpt] = (ev.step, ev.value)

    top = sorted(by_ckpt.items(), key=lambda kv: kv[1][1], reverse=True)[:args.top_n]
    if args.sort == "ckpt":
        top.sort(key=lambda kv: kv[0])
    ranked = top

    print(f"\n=== top {args.top_n} checkpoints for {path.name} ({args.tag}) ===\n")
    print(f"  {'rank':>4s}  {'file':<10s}  {'value':>8s}  {'step':>10s}  status")
    print(f"  {'-'*4}  {'-'*10}  {'-'*8}  {'-'*10}  {'-'*8}")
    for rank, (ckpt, (step, value)) in enumerate(ranked, start=1):
        f = path / f"ppo{ckpt}.pt"
        status = "ok" if f.exists() else "MISSING"
        print(f"  {rank:>4d}  ppo{ckpt}.pt  {value:>8.2f}  {step:>10d}  {status}")
    print()


if __name__ == "__main__":
    main()
